### ISSUE TITLE
Trinkets Integration Not Working

### ISSUE THREAD

**Issue by TheEmeraldBee** [JackFred2/LenientDeath#13]
## Version 
1.21
## Mod Version
1.2.4

# Issue
When I die, I get a Error saying that a command could not be executed.

Mods include:
Lenient Death
Artifacts
Trinkets

# Logs
None Generated for the error, no crash, no error in logs

**Comment by JackFred2** [comment]
Can't reproduce; additionally Lenient Death doesn't run any commands when you die so I suspect it might be another mod or datapack. If you hover over the 'command could not be executed' vanilla normally shows part of the error.

Used versions:
![image](https://github.com/user-attachments/assets/0e35f85d-6a6d-4c7c-813b-e31f7599ac04)

**Comment by TheEmeraldBee** [comment]
There is a chance that it could be from a 3-way mod conflict, but for me, removing either Artifacts + Trinkets, or just removing Lenient Death fixes the issue. The part of the error is a no value present error.

**Comment by JackFred2** [comment]
I've pushed an update that fixes a similar trinkets issue; you can see if it works for you now?

**Comment by TheEmeraldBee** [comment]
Yep! I'll close the issue as resolved. Thank you so much!
