### ISSUE TITLE
[Feature Request] Per-Player Keep Inventory

### ISSUE THREAD

**Issue by Pete3R** [JackFred2/LenientDeath#2]
Allow players on Multiplayer servers to toggle whether they want/do not want keep inventory to be applied to them.
Similarly to: https://modrinth.com/mod/freedomofinsomnia that works for Phantoms

**Comment by JackFred2** [comment]
Added in 0.9.0, use by enabling with `/ld perPlayer true`, then each player can disable/enable with `/ld disableForMe` / `/ld enableForMe` respectively.
