### ISSUE TITLE
Add support to NBT tags

### ISSUE THREAD

**Issue by AppleInTheSky** [JackFred2/LenientDeath#3]
I want to make something like, if you have 2 swords, and one of them has a tag in his nbt that is "soulbound:1b", and you die, you will lost only the sword that doesn't have that tag, thank you (Idk if you still support preview versions like 1.17.1, but i hope you do ^^)

**Comment by JackFred2** [comment]
little bit late but implemented for v1.x.x; under `$.preserveItemsOnDeath.nbt`
