### ISSUE TITLE
PerPlayer settings do not save and reset on each reconnect 

### ISSUE THREAD

**Issue by reykz96** [JackFred2/LenientDeath#4]
Every time either me or my players rejoin the server the settings reset. Only one of us uses Lenient Death and the rest want to disable it but we need to to enter the command every time we enter the server to disable it.

**Comment by JackFred2** [comment]
Think I found the issue; the per player mode wasn't copying over when a new Player Entity was made (death/connect/dimension change); I'll push a fix now

**Comment by JackFred2** [comment]
Fixed in 4b92b5965eeb67399fe6371ed1da434a57d96dfe

**Comment by reykz96** [comment]
Thank you so much! Awesome mod!
