### ISSUE TITLE
[Feature] Death Coordinates

### ISSUE THREAD

**Issue by Developer-Mike** [JackFred2/LenientDeath#5]
It would be cool if the death coordinates show up in the chat. Because this mod should make dying more forgiving, it would be a perfect addition.

**Comment by JackFred2** [comment]
added in 1a42fb1e44cc41fc868461bbe3eae3a4f26f2a2b, released in 1.0.4

**Comment by Developer-Mike** [comment]
Is it possible to log the messages in the server log?

**Comment by JackFred2** [comment]
can add it when I get homeOn 28 Oct 2023 16:09, "Mike." ***@***.***> wrote:
Is it possible to log the messages in the server log?

**Comment by JackFred2** [comment]
added in d88791f005b5cd532b1ab5f2d9c0ad3defb35c8d
