### ISSUE TITLE
Why /ld config doesn`t work

### ISSUE THREAD

**Issue by Misha4ek** [JackFred2/LenientDeath#6]
Pretty self explanatory.
I have 1.20.1 minecraft version. 0.20.1 quilt
I just downloaded lenientdeath-1.20.1-0.9.4.jar and dropped it in server mods folder.
server is runing on my PC (have no troubles)

![javaw_t4lYYYJ5EH](https://github.com/JackFred2/LenientDeath/assets/39009568/17acfff5-b7f2-442b-be07-d225ec67b1ba)

**Comment by JackFred2** [comment]
my bad; the wiki is for the 1.20.2 rewrite of LD. you can find docs for the old config [here](https://github.com/jackfred2/lenientdeath/tree/legacy-1.x#configuration). I'll add a heads up in the readme later.

**Comment by Misha4ek** [comment]
Understandable. Soo any plans for updating older versions?

**Comment by Misha4ek** [comment]
I see that older versions have only keepinventory item filtering, correct?

**Comment by JackFred2** [comment]
Possibly to 1.20.1 and 1.19.4, no further.

Correct.

On 28 Oct 2023 20:56, Misha4ek ***@***.***> wrote:
I see that older versions have only keepinventory item filtering, correct?
