### ISSUE TITLE
Feature: Bell curve distribution stack split on death

### ISSUE THREAD

**Issue by TULACIO** [JackFred2/LenientDeath#7]
I don't know if this is what you already meant by "Randomizer: stack splitting" on your To Do list. Sorry if that is the case.
I was sort of sad that the current version is always binary for every inventory slot, and neatly, if you were to include "per item" chance of drop, they would naturally follow a bell curve, always dropping some food, but also always keeping some. 
For the sake of PvP balance I disabled food dropping on my server, but this option would keep everyone happy.

**Comment by JackFred2** [comment]
That's what I meant yeah; simulating the drop chance for each individual item. Will need some tinkering (each slot is currenly either drop or no drop, not a mix), but I'll try push it out before 1.20.3 next week

**Comment by JackFred2** [comment]
Added for 1.1.1
![5xxwHfG4NH](https://github.com/JackFred2/LenientDeath/assets/8350692/5a958856-3652-4784-af70-3193f65ca4ce)
