### ISSUE TITLE
[Crash] Crashed when dropping tons of items on Random

### ISSUE THREAD

**Issue by lostdoge08** [JackFred2/LenientDeath#9]
I have the random setting enabled, and made it to where I only keep 10% of my inventory, and it is rolled for each individual item in a stack. I also removed the items that are guaranteed to be kept, adding more randomness. I died with multiple stacks of items in my inventory, which crashed my game. When loading back in, everything seemed to be fine, and the items were gone like normal.

Here is the crash log 
[ccrash-2024-06-14_01.19.03-server.txt](https://github.com/user-attachments/files/15833317/ccrash-2024-06-14_01.19.03-server.txt)

And here is my config (changed from json5 to json so i could upload it)
[lenientdeath.json](https://github.com/user-attachments/files/15833575/lenientdeath.json)

**Comment by JackFred2** [comment]
Can't reproduce (seems to be another mod doing something similar), but i've added a check about where the crash is which should fix this.
